import Header from "@/components/Shared/Header";
import SideBar from "@/components/Shared/SideBar";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<Header />
				<div className="bg-[#ebeafb]">
					<div className="flex gap-6 mx-[5vw] pt-10">
						<SideBar />
						{children}
					</div>
				</div>
			</body>
		</html>
	);
}
